[0.000000] (-) TimerEvent: {}
[0.001459] (-) JobUnselected: {'identifier': 'mr2_launch'}
[0.001954] (-) JobUnselected: {'identifier': 'mr2_realsense'}
[0.002053] (-) JobUnselected: {'identifier': 'yolobot_recognition'}
[0.002449] (-) JobUnselected: {'identifier': 'yolov8_msgs'}
[0.002615] (buffalo_robot) JobQueued: {'identifier': 'buffalo_robot', 'dependencies': OrderedDict()}
[0.002769] (buffalo_robot) JobStarted: {'identifier': 'buffalo_robot'}
[0.099427] (-) TimerEvent: {}
[0.200933] (-) TimerEvent: {}
[0.301637] (-) TimerEvent: {}
[0.402301] (-) TimerEvent: {}
[0.502968] (-) TimerEvent: {}
[0.603605] (-) TimerEvent: {}
[0.704298] (-) TimerEvent: {}
[0.805003] (-) TimerEvent: {}
[0.906024] (-) TimerEvent: {}
[1.007150] (-) TimerEvent: {}
[1.108542] (-) TimerEvent: {}
[1.209266] (-) TimerEvent: {}
[1.310025] (-) TimerEvent: {}
[1.410694] (-) TimerEvent: {}
[1.511422] (-) TimerEvent: {}
[1.612061] (-) TimerEvent: {}
[1.712707] (-) TimerEvent: {}
[1.813353] (-) TimerEvent: {}
[1.913986] (-) TimerEvent: {}
[2.014726] (-) TimerEvent: {}
[2.083810] (buffalo_robot) StderrLine: {'line': b'Traceback (most recent call last):\n  File "/usr/lib/python3/dist-packages/colcon_parallel_executor/executor/parallel.py", line 75, in execute\n    loop.run_until_complete(future)\n  File "/usr/lib/python3.8/asyncio/base_events.py", line 603, in run_until_complete\n    self.run_forever()\n  File "/usr/lib/python3.8/asyncio/base_events.py", line 570, in run_forever\n    self._run_once()\n  File "/usr/lib/python3.8/asyncio/base_events.py", line 1823, in _run_once\n    event_list = self._selector.select(timeout)\n  File "/usr/lib/python3.8/selectors.py", line 468, in select\n    fd_event_list = self._selector.poll(timeout, max_ev)\nKeyboardInterrupt\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/usr/lib/python3/dist-packages/colcon_core/executor/__init__.py", line 91, in __call__\n    rc = await self.task(*args, **kwargs)\n  File "/usr/lib/python3/dist-packages/colcon_core/task/__init__.py", line 93, in __call__\n    return await task_method(*args, **kwargs)\n  File "/usr/lib/python3/dist-packages/colcon_ros/task/ament_python/build.py", line 102, in build\n    return await extension.build(additional_hooks=additional_hooks)\n  File "/usr/lib/python3/dist-packages/colcon_core/task/python/build.py", line 90, in build\n    available_commands = await self._get_available_commands(\n  File "/usr/lib/python3/dist-packages/colcon_core/task/python/build.py", line 188, in _get_available_commands\n    output = await check_output(\n  File "/usr/lib/python3/dist-packages/colcon_core/subprocess.py", line 129, in check_output\n    assert not rc, f\'Expected {args} to pass: {stderr_data}\'\nAssertionError: Expected [\'/usr/bin/python3\', \'-W\', \'ignore:setup.py install is deprecated\', \'setup.py\', \'--help-commands\'] to pass: Traceback (most recent call last):\n  File "setup.py", line 6, in <module>\n    setup(\n  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 144, in setup\n    return distutils.core.setup(**attrs)\n  File "/usr/lib/python3.8/distutils/core.py", line 134, in setup\n    ok = dist.parse_command_line()\n  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 707, in parse_command_line\n    result = _Distribution.parse_command_line(self)\n  File "/usr/lib/python3.8/distutils/dist.py", line 480, in parse_command_line\n    if self.handle_display_options(option_order):\n  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 1092, in handle_display_options\n    return _Distribution.handle_display_options(self, option_order)\n  File "/usr/lib/python3.8/distutils/dist.py", line 683, in handle_display_options\n    self.print_commands()\n  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 843, in print_commands\n    cmdclass = ep.resolve()\n  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve\n    module = __import__(self.module_name, fromlist=[\'__name__\'], level=0)\n  File "/usr/lib/python3/dist-packages/setuptools/command/test.py", line 6, in <module>\n    import unittest\n  File "/usr/lib/python3.8/unittest/__init__.py", line 60, in <module>\n    from .async_case import IsolatedAsyncioTestCase\n  File "/usr/lib/python3.8/unittest/async_case.py", line 1, in <module>\n    import asyncio\n  File "/usr/lib/python3.8/asyncio/__init__.py", line 8, in <module>\n    from .base_events import *\n  File "/usr/lib/python3.8/asyncio/base_events.py", line 40, in <module>\n    from . import events\n  File "/usr/lib/python3.8/asyncio/events.py", line 21, in <module>\n    from . import format_helpers\n  File "<frozen importlib._bootstrap>", line 1017, in _handle_fromlist\nKeyboardInterrupt\n\n'}
[2.086282] (buffalo_robot) JobEnded: {'identifier': 'buffalo_robot', 'rc': 'SIGINT'}
[2.095585] (-) EventReactorShutdown: {}
